robot:
  type: so100_follower
  port: /dev/ttyACM1
  id: my_awesome_follower_arm
  cameras:
    front:
      type: opencv
      index_or_path: 0
      width: 640
      height: 480
      fps: 30

dataset:
  repo_id: Baptiste-le-Beaudry/eval_lekiwi
  single_task: center_over_block

policy:
  type: act
  pretrained_path: Baptiste-le-Beaudry/act_lekiwi_full

display_data: false
